environment:
  matrix:
    # Python 2.7
    - PYTHON: "C:\\Python27"
      PYTHONIOENCODING: "UTF-8"
    - PYTHON: "C:\\Python27-x64"
      PYTHONIOENCODING: "UTF-8"

    # Python 3.5
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

    # Python 3.6
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

    # Python 3.7
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    
    # Python 3.8
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

max_jobs: 1

test_script:
  - "%PYTHON%\\python.exe setup.py install"
  - "%PYTHON%\\Scripts\\pipwin.exe refresh --log=info"
  - "%PYTHON%\\Scripts\\pipwin.exe search babel"
  - "%PYTHON%\\Scripts\\pipwin.exe install babel>=2.0"
  - "echo y | %PYTHON%\\Scripts\\pipwin.exe uninstall babel"
  # First package:
  - "%PYTHON%\\Scripts\\pipwin.exe search ad3"
  # Last package:
  - "%PYTHON%\\Scripts\\pipwin.exe search zstd"
  # Last Misc package:
  - "%PYTHON%\\Scripts\\pipwin.exe search zope.exceptions"
